### ISSUE TITLE
Make an intro

### ISSUE THREAD

**Issue by privettalon** [privettalon/homepage#5]
Make an intro. It must be a short, 2-4 sentence about Trump, what he likes to do, what wants to do better, etc.

**Comment by olexander-kovalchuk** [comment]
Зараз я напишу тобі 2-4 речення, як ти мене задовбав. Пишеш собі там якусь фігню, то мене хоч не чіпай, а то мамі розкажу. До речі, твій шматок торту такий смачний, ти б знав.
