### ISSUE TITLE
Make additional information blocks

### ISSUE THREAD

**Issue by privettalon** [privettalon/homepage#8]
You can make the resume less formal by adding additional blocks that contain useful information but present it in an "entertaining" form. For example, what you like and dislike, strengths and weaknesses, a list of skills or hobbies, infographics or interactive modules, and so on. It is worth writing the content of such a block before starting the layout because its size will affect the placement of elements on the page.

**Comment by olexander-kovalchuk** [comment]
Все що я зможу зробити додатково, це з'їсти твою паску. Відстань
